### PR TITLE
Added medianMaintenance

### PR DESCRIPTION
**Pull request by AksanaKuzmitskaya**

### CODE REVIEW

**Comment by sarahzinger** [comment]
@AksanaKuzmitskaya what is Median.txt ?

**Comment by sarahzinger** [comment]
In the interest of time I'm just going to merge this and delete txt ok? Thanks so much for contributing!! @AksanaKuzmitskaya

**Comment by AksanaKuzmitskaya** [comment]
Median  is needed in order to solve the problem which has numbers there that are used for the problem.

**Comment by sarahzinger** [comment]
Ah! ok cool my bad!

**Pull request merged**
