### PR TITLE
add new solution

### PR DESCRIPTION
**Pull request by IuliiaKot**
Added the solution for problem 3 and fixed typo for problem 4

### CODE REVIEW

**Comment by sarahzinger** [comment]
Hey @IuliiaKot this looks great but we've got a merge conflict. If you can resolve those merge conflicts and push up an updated version I'd be happy to merge in your solution :) If you need any help with how to do that let me know. I'd be happy to show ya how

**Comment by IuliiaKot** [comment]
Hi @sarahzinger . Please, could you show me how to do it. I never did it before. Thank you.

**Comment by sarahzinger** [comment]
@IuliiaKot 
1. git checkout master (this goes onto your local version of master)
2. git pull origin master (this updates your local master with the real master on github)
3. git checkout whatever you named your branch for this pull request (I think it was addsolution or somehting like that). If you aren't sure what it's called you can do git branch and it will list all of the ones you have.
4. git rebase master
this will likely tell you that you have conflicts. But don't panic go into the files that are labeled CONFLICT (you'll see it in the command line) and fix them up so that they look like however you think they should. It'll do something like this:

```
<<<<<<<<<<<<<<head
code version 1
===============
code version 2
<<<<<<<<<<<<<<<name of your branch.
```

What's happening is that git isn't smart enough to know which version of the code you want. Just delete all of the extra characters and extra versions of the code and pick the lines you want. 
5. git add -Av
6. If you're still in the middle of a rebase do git rebase --continue
7. git push origin the-name-of-whatever-your branch-is

If you get stuck or lost at any time you can do git --abort or just contact me and we can do a google hangout or something. Or if you're not into this I can just add the code myself, though personally I think it's awesome to learn how to use github and would be happy to help out!

**Comment by IuliiaKot** [comment]
Hi @sarahzinger, thank you for this great instruction. But it still doesn't work. Maybe
I missed something. It would be greate to do a  google hangout because I
would like to learn how to do and what I missed now. Thank you.

**Comment by sarahzinger** [comment]
Cool no worries it's tricky to explain why don't you shoot me an email and we can set up a time to talk for ten minutes :) sarah.a.zinger@gmail.com

**Comment by sarahzinger** [comment]
Cool, closing this one out :)

**Pull request closed without merging**
