### PR TITLE
bitTricks.cpp

### PR DESCRIPTION
**Pull request by harrypotter0**
Bits manipulation (Important tactics)

### CODE REVIEW

**Comment by harrypotter0** [comment]
Bits manipulation (Important tactics)

**Comment by sarahzinger** [comment]
@harrypotter0 Hey there! Looks like something funky happened with your branch! Oh no :smile: Want to try again?

Make sure your branche is based on the lastest master branch and that you are making your pr on github with your particular branch :) It looks like you're trying to merge a branch called June into master, which doesn't seem quiet right. Feel free to make another pull request or update this one whichever is easiest :)

Also if you need help let me know and I can try to help you out either in person at our next Algorithms event or via google hangouts or something.

**Review by harrypotter0 — COMMENTED** [review]
what's the status on this ?

**Comment by harrypotter0** [comment]
Bits manipulation (Important tactics)

**Pull request closed without merging**
