### PR TITLE
Create Problem6.md

### PR DESCRIPTION
**Pull request by AksanaKuzmitskaya**

### CODE REVIEW

**Comment by sarahzinger** [comment]
Hey @AksanaKuzmitskaya a couple small suggestions? Would you mind adding a solution (any language) for this problem as well as some more background on what quick sort is for those who aren't familiar?

**Comment by AksanaKuzmitskaya** [comment]
Yes, sure. Will do it. Thank you

**Comment by sarahzinger** [comment]
@AksanaKuzmitskaya since the event is tomorrow I'm going to merge this pull request as is and add some stuff myself later. But if you have a solution you want to add you definitely should :smile:

**Comment by AksanaKuzmitskaya** [comment]
oh, sorry, thought that event is on Thursday.

**Pull request merged**
