### PR TITLE
Update Problem4.md

### PR DESCRIPTION
**Pull request by AksanaKuzmitskaya**

### CODE REVIEW

**Comment by sarahzinger** [comment]
Cool looks good. Also just as a heads up it's totally possible to update a pr rather than making two :)

**Comment by AksanaKuzmitskaya** [comment]
Yes, sorry, did not have much time, since I don't use Github that often, it takes time to figure how to add stuff, so I added everything using the browser. 

Thanks

**Comment by sarahzinger** [comment]
@AksanaKuzmitskaya no need to apologize! Just wanted to make sure you knew it was possible. All you gotta do is stay on the branch that your PR is on, add another commit and push up that branch again and  the PR you made will automatically get updated which is pretty cool. If you're stopping by tonight I could show you for next time if you're interested :) but no pressure separate prs is just fine!

**Comment by AksanaKuzmitskaya** [comment]
Hi Sarah,

I am planning to stop by tomorrow and it would be great if you could show
me how to submit problems, I really like to do it.
Also, I am on a waitlist for tomorrow's event, do you think I will be able
to get in?
Do you need any help for tomorrow? Not sure if I have time to submit
problems for tomorrow though.

Thank you so much!

On Thu, Feb 18, 2016 at 5:16 PM, Sarah Zinger notifications@github.com
wrote:

> @AksanaKuzmitskaya https://github.com/AksanaKuzmitskaya no need to
> apologize! Just wanted to make sure you knew it was possible. All you gotta
> do is stay on the branch that your PR is on, add another commit and push up
> that branch again and the PR you made will automatically get updated which
> is pretty cool. If you're stopping by tonight I could show you for next
> time if you're interested :) but no pressure separate prs is just fine!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WomenWhoCodeNYC/Algorithms/pull/53#issuecomment-185948359
> .

## 

Thank you for your time and consideration.

Sincerely,
_Aksana Kuzmitskaya_
New York, NY
Email: aksana.kuzmitskaya@gmail.com
Cell: (347) 828-4730

**Pull request merged**
