### PR TITLE
Adding few problems for August Month event

### PR DESCRIPTION
**Pull request by rupalgupta15**
Kindly review

### CODE REVIEW

**Comment by sarahzinger** [comment]
Hi @rupalgupta15 this is looking pretty good :) Before we merge this though, would you mind making a few changes?

- Can you place all of the problems in their own separate folders inside the "challenges" folder. You can then create links to them with markdown. This allows us to reuse problems from month to month. For more on our file structure and naming conventions, please check out the [Contributing Problems and Solutions section](https://github.com/WomenWhoCodeNYC/Algorithms/blob/master/howToContribute.md#contributing-problems-and-solutions-to-the-repo) of our How To Contribute Guide.
- Just a heads up I noticed you are submitting some problems that I believe we have already done (Towers of Hanoi) for example :) Feel free to double check if there are any repeats, if there are just use the old files, no need to make another one :)
- For the new problems would it be possible to also submit a solution?

Thanks so much! Excited for it. Also as a reminder we had to move Algorithms from this Thursday to next Wednesday. Thanks!!! 🎉

**Comment by rupalgupta15** [comment]
Hi Sarah,

Thank you for the feedback. I'll make the required changes.

Regarding repetition of problems, I'll make sure the problems I post do not
coincide with already discussed problems. I'll identify a new problem and
solutions for the others as well.

Have a great day :)
Rupal

**Comment by rupalgupta15** [comment]
Hi @sarahzinger, I have separated the problems into their own folders and also added solutions. Please review. 
Hope this helps :)

**Comment by rupalgupta15** [comment]
Hi Sarah,
I have made the changes and separated the problems into own folders along
with their solutions.
Please review.

Thanks!
Rupal

**Comment by sarahzinger** [comment]
Thanks @rupalgupta15 I'll merge it and add the problems to tonight's event! 🎈 😄 🎉

**Comment by rupalgupta15** [comment]
Hi Sarah, 

Thank you for merging the request. One correction is required though. In the Link to this month's problem, the link for the problem - ContainsDuplicate is incorrect (misspelled to constains)

Its stated : https://github.com/WomenWhoCodeNYC/Algorithms/blob/master/challenges/constainsDuplicate/constainsDuplicate.md

Actual link is : 
https://github.com/WomenWhoCodeNYC/Algorithms/blob/master/challenges/containsDuplicate/containsDuplicate.md

**Pull request merged**
