### PR TITLE
Update and rename Problem2.md to Problem2.js

### PR DESCRIPTION
**Pull request by kikoorikoo**
recursive js solution

### CODE REVIEW

**Comment by sarahzinger** [comment]
@kikoorikoo Thanks for submitting a solution! Love the recursion! Would you mind putting this in the Solutions file? We already have a js file if you want to just add it there with a comment that it's a recursive solution? It's in `Algorithms/October-22-2015/Solutions/Problem2.js` Let me know if you want help!

**Comment by kikoorikoo** [comment]
@smuenzinger Thanks! Yes, I pretty much need step-by-step instructions.

**Comment by sarahzinger** [comment]
@kikoorikoo Just cut and paste your solution into `Algorithms/October-22-2015/Solutions/Problem2.js` and save the file you were writing in back to a .md instead of a .js file (this way people can look at the problem without seeing the solution right away). Save everything and Add and Commit your changes (`git add -A` and `git commit -m") and then push your branch back up. The pull request should automatically update. Let me know if you run into trouble!

**Comment by kikoorikoo** [comment]
@smuenzinger As far as I can tell, i did it. I don't have access to CLI git on the computer I'm currently working on, so I did it all in the github web interface.

**Comment by sarahzinger** [comment]
You did it! I'm gunna do some minor clean up for ya but thanks @kikoorikoo You're a super :star:

**Comment by kikoorikoo** [comment]
Awesome, thanks!

**Pull request merged**
